### ISSUE TITLE
Support for ideal without issuers?

### ISSUE THREAD

**Issue by Dokujin** [buckaroo-it/Magento2_Hyva_Checkout#64]
It seems like the MageWire Model always validates for an issuer even if the setting in buckaroo is turned off. The template also does not check for this setting and always renders the issuers in either a select or radio buttons.

**Comment by Buckaroo-Rene** [comment]
Hi @Dokujin ,

Thanks for informing us about this issue.
We are aware of this issue and a fix has already being implemented with reference: BP-4215.
This will be resolved with a new release, that we are currently preparing.

**Comment by Buckaroo-Rene** [comment]
Hi @Dokujin ,

This is resolved in version [1.3.1](https://github.com/buckaroo-it/Magento2_Hyva_Checkout/releases/tag/v1.3.1).

**Comment by AlbinaBaraliu** [comment]
Hi @robhuijben, 

If you're still seeing the problem, please make sure to:

Clear the Magento cache:
bin/magento cache:clean && bin/magento cache:flush

Recompile if in production mode:
bin/magento setup:di:compile

And deploy static content if needed:
bin/magento setup:static-content:deploy

Let us know if the issue persists after those steps!

**Comment by robhuijben** [comment]
I did all of above, but the issue still remains the same.

For your info, I am using M2.4.6-p9, Hyvä Checkout version 1.1.26.

**Comment by Buckaroo-Rene** [comment]
Hi @robhuijben ,

We've tried to reproduce the issue you are facing with the exact same versions as you specified.
However we were still not able to reproduce it since it is working fine for us.
Do you have a staging available where we can check this out to help you further with this issue?

If yes, please send us an e-mail with the information about this issue and the staging information, so we can look for a solution from there. You can send the e-mail to: [support@buckaroo.nl](mailto:support@buckaroo.nl)

Please let me know here as well when the e-mail has been send, since the e-mail will be send to my colleagues from the technical support department.

Best Regards,
René

**Comment by robhuijben** [comment]
My bad, mist an override file in the theme dir. Apologies!

**Comment by Buckaroo-Rene** [comment]
Hi @robhuijben ,

All good — thanks for the follow-up, and no worries at all! Glad it was just a simple oversight.
Appreciate you letting us know! 🙌
